name: ci
on: [push]

jobs:
  install:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: brew install clojure
      - run: clojure -Atest
